spring.application.name=smartcollect

server.port=8084

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=trace


spring.mvc.apiversion.use.header=API-Version
spring.mvc.apiversion.default=1.4

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

logging.level.demo.DemoServiceImpl=trace
logging.level.org.springframework.data.mongodb.core.MongoTemplate=trace

###########
# profiles
###########
### use this configuration to have server initialize data on startup
spring.profiles.active=default,initDemoes

### use this configuration for booting a server without data initialization
#spring.profiles.active=default


#######################
### JPA Configuration
#######################
### configure JPA to work with Postgresql Database
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=trace

### --------------------------------------------------------------------------
### Sprint 4 Environment Toggle - Smart Collect
### --------------------------------------------------------------------------
### [State 1: Development & Testing] - DB is dropped and recreated on startup
#spring.jpa.hibernate.ddl-auto=create-drop

### [State 2: Production Submission] - Data is persisted 
#spring.jpa.hibernate.ddl-auto=update
### --------------------------------------------------------------------------

### production configuration (step1)
spring.jpa.hibernate.ddl-auto=create

### production configuration (step2)
#spring.jpa.hibernate.ddl-auto=validate

### enable helper web console for database validation for testing only
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console